name: Postman collection workflow test
on:
  push:
    branches:
      - main
      - feature/*
jobs:
  newman_run: 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4.0.0
        
      - name: Setup Node.js environment
        uses: actions/setup-node@v3.8.1
        with: 
          node-version: '18'
      - name: Install Newman & HTML reporter
        run: |
          npm install -g newman 
          npm install -g newman-reporter-htmlextra 
      - name: Run tests 
        run: newman run Postman/Lesson3_Mukhangaliyeva.postman_collection.json -r cli,htmlextra,junit 
      # Deploy to GH pages
      - name: Checkout to gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      - name: Copy report to the gh-pages branch
        if: always()
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build-dir: newman
        env: 
          GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
      - name: Deploy the report from the gh-pages branch to the website
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env: 
          PERSONAL_TOKEN: ${{secrets.GH_TOKEN}}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: newman
        
